# Default values for helm-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
appName: apiserver
creator: raihan
version: 1.0.0
container:
  name: ecommerce-container
  image: raihankhanraka/ecommerce-api
  tag: v1.1

service:
  port: 8084
  nodePort: 8083

ingress:
  enabled: true
  hosts:
    - host: raka.com
      paths:
        - path: /login
          pathType: ImplementationSpecific
        - path: /products
          pathType: ImplementationSpecific
