apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName | lower }}-deployment
  labels:
    app.kubernetes.io/name: {{ .Values.appName | lower }}
    app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
    app.kubernetes.io/created-by: {{ .Values.creator | lower }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName | lower }}
      app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
      app.kubernetes.io/created-by: {{ .Values.creator | lower }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/version: {{ .Values.version | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName | lower }}
        app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
        app.kubernetes.io/created-by: {{ .Values.creator | lower }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Values.version | quote }}

    spec:
      containers:
        - name: {{ .Values.container.name | quote }}
          image: "{{.Values.container.image}}:{{.Values.container.tag}}"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.appName | lower }}-nodeport
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName | lower }}
    app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
    app.kubernetes.io/created-by: {{ .Values.creator | lower }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Values.version | quote }}

  type: NodePort
  ports:
    - protocol: TCP
      port: {{.Values.service.nodePort | default 8080}}
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName | lower }}-svc
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName | lower }}
    app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
    app.kubernetes.io/created-by: {{ .Values.creator | lower }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080

---
  {{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Values.appName | lower }}
    app.kubernetes.io/instance: {{ .Values.appName | lower }}-deployment
    app.kubernetes.io/created-by: {{ .Values.creator | lower }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.appName | lower }}-svc
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- end }}
---